### ISSUE TITLE
Provide project in PyPI

### ISSUE THREAD

**Issue by pamagister** [pamagister/Photo-Composition-Designer-Backup#58]
Damit dein GitHub-Python-Projekt erfolgreich auf **PyPI (Python Package Index)** hochgeladen wird, musst du einige Schritte befolgen. Hier ist eine vollständige Anleitung:

---

### **Erstelle die notwendige Projektstruktur**
Dein Repository sollte etwa so aussehen:
```
mein-projekt/
│── mein_projekt/        # Hauptmodul
│   ├── __init__.py
│   ├── main.py
│── tests/               # Tests
│── pyproject.toml       # Metadaten (Empfohlen für moderne Pakete)
│── setup.py             # Alternativ, falls kein `pyproject.toml` genutzt wird
│── setup.cfg            # Konfigurationsdatei (Optional)
│── README.md            # Projektbeschreibung (Wird auf PyPI angezeigt)
│── LICENSE              # Lizenzdatei
│── .gitignore
│── requirements.txt     # Abhängigkeiten (falls nötig)
```
Falls du mit **Poetry** arbeitest, brauchst du keine `setup.py`, sondern nutzt `pyproject.toml`.

---

### **Option 1: Mit `pyproject.toml` (empfohlen)**
Erstelle oder editiere die Datei `pyproject.toml`:
```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mein_projekt"
version = "0.1.0"
description = "Mein erstes Python-Paket für PyPI"
authors = [{ name = "Dein Name", email = "deine@email.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "requests",
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/dein-github/mein-projekt"
"Bug Tracker" = "https://github.com/dein-github/mein-projekt/issues"
```
### **Option 2: Mit `setup.py` (ältere Methode)**
Falls du `setup.py` nutzt, erstelle oder editiere die Datei:
```python
from setuptools import setup, find_packages

setup(
    name="mein_projekt",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "requests",
        "numpy",
    ],
    author="Dein Name",
    author_email="deine@email.com",
    description="Mein erstes Python-Paket für PyPI",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/dein-github/mein-projekt",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
```

---

## **3. Erstelle ein `LICENSE`- und `README.md`-File**
PyPI benötigt eine Lizenz und eine README-Datei für die Paketbeschreibung.

- **Lizenz (`LICENSE`)**: Wähle eine Lizenz (z. B. MIT):
  ```
  MIT License

  Copyright (c) 2025 Dein Name
  ```

- **README.md**: Wird auf PyPI als Beschreibung angezeigt. Beispiel:
  ```md
  # Mein Projekt
  Dieses Python-Paket macht XYZ...
  ```

---

## **4. Baue das Paket**
Installiere **`build`**, falls nicht bereits installiert:
```sh
pip install build
```
Erstelle dann das Paket:
```sh
python -m build
```
Das erzeugt zwei Dateien in `dist/`, z. B.:
```
dist/
│── mein_projekt-0.1.0-py3-none-any.whl
│── mein_projekt-0.1.0.tar.gz
```

---

### **Erstelle ein PyPI-Konto**
Falls noch nicht geschehen, registriere dich auf **[PyPI](https://pypi.org/account/register/)** und erstelle eine **API-Token** unter:
👉 https://pypi.org/manage/account/#api-tokens  
Speichere den **Token**, z. B. `pypi-XXXXXXXXXXXXXXXXXXXXXXXXXXXX`.

### **Installiere `twine` und lade das Paket hoch**
```sh
pip install twine
```
Hochladen mit:
```sh
twine upload dist/*
```
Falls nach Benutzername/Passwort gefragt wird, gib dein **API-Token** als Passwort ein und lasse den Benutzernamen leer.

---

## **6. Teste die Installation**
Nach erfolgreichem Upload kannst du dein Paket mit **pip** installieren:
```sh
pip install mein_projekt
```
Falls du erst auf **TestPyPI** hochgeladen hast, teste mit:
```sh
pip install --index-url https://test.pypi.org/simple/ mein_projekt
```

---

## **7. Automatisierung mit GitHub Actions**
Falls du dein Paket automatisch mit jedem Release hochladen willst, erstelle eine Datei **`.github/workflows/pypi.yml`**:

```yaml
name: Upload Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
```
**Wichtig:**  
- Erstelle in GitHub unter **Settings → Secrets → Actions** ein Secret namens `PYPI_API_TOKEN` mit deinem PyPI-Token.

---

## **Fazit**
🚀 **Nach diesen Schritten ist dein Python-Paket erfolgreich auf PyPI!**  
Zusammenfassung:
1. Projektstruktur prüfen (`mein_projekt/`, `pyproject.toml` oder `setup.py`)
2. Paketinformationen (`pyproject.toml` oder `setup.py`)
3. **Lizenz** und **README.md** erstellen
4. Paket mit `python -m build` erstellen
5. Mit `twine upload dist/*` zu **PyPI** hochladen
6. Paket mit `pip install mein_projekt` testen
7. Optional: **GitHub Actions** für automatischen Upload

Jetzt können andere dein Paket mit `pip install mein_projekt` installieren! 🎉
