### ISSUE TITLE
Provide project as installable Windows EXE

### ISSUE THREAD

**Issue by pamagister** [pamagister/Photo-Composition-Designer-Backup#59]
Ja, du kannst dein Python-Projekt als **Windows-EXE** bauen und releasen. Dafür gibt es verschiedene Tools, aber die beliebtesten sind:

1. **PyInstaller** (empfohlen für die meisten Fälle)  
2. `cx_Freeze`  
3. `py2exe` (weniger populär)  

---

## **1. Installation von PyInstaller**
Zunächst installierst du `pyinstaller` in deiner Entwicklungsumgebung:
```sh
pip install pyinstaller
```

---

## **2. Erstelle eine EXE-Datei**
Navigiere in dein Projektverzeichnis und führe folgenden Befehl aus:
```sh
pyinstaller --onefile --windowed main.py
```
Erklärung:
- `--onefile` → Erstellt eine einzelne `.exe`-Datei.
- `--windowed` → Keine Konsolenanzeige (für GUI-Anwendungen). Falls deine App eine **CLI** ist, lasse diesen Parameter weg.

Nach Abschluss findest du die EXE-Datei in:
```
dist/main.exe
```

### **Erweitertes Beispiel (mit Icon & Name)**
Falls du eine eigene **EXE-Icon-Datei** (`icon.ico`) verwenden willst:
```sh
pyinstaller --onefile --windowed --name "MeinProgramm" --icon=mein_icon.ico main.py
```

---

## **3. Automatisierung mit GitHub Actions**
Falls du dein Programm automatisch als EXE builden und releasen willst, erstelle eine Datei `.github/workflows/windows-build.yml`:

```yaml
name: Build EXE and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --name MeinProgramm main.py

      - name: Upload EXE to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MeinProgramm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### **Erklärung**
- Baut automatisch eine EXE-Datei bei jedem Git-Tag (`v1.0.0` etc.).
- Lädt die EXE als **Release-Asset** auf GitHub hoch.

---

## **4. EXE testen & verteilen**
Nach dem Build kannst du deine `dist/main.exe` testen und verteilen:
✅ Direkt per **E-Mail/Cloud** verschicken  
✅ In ein **ZIP-Archiv** packen  
✅ Auf **GitHub Releases** hochladen  
✅ Als **Installer** mit `Inno Setup` oder `NSIS` verpacken  

Falls dein Programm nicht startet, überprüfe die **fehlenden DLLs** mit:
```sh
pyinstaller --onefile --debug=all main.py
```

---

## **Fazit**
Ja, du kannst dein **Python-Projekt als Windows-EXE** bauen und releasen! 🚀  
Nutze **PyInstaller** für eine einfache Lösung oder automatisiere den Prozess mit **GitHub Actions**.

🔥 Jetzt kannst du dein Programm ohne Python-Installation weitergeben! 🎉
