### ISSUE TITLE
MyPy: activate mypy type check

### ISSUE THREAD

**Issue by pamagister** [pamagister/Photo-Composition-Designer-Backup#63]
Damit dein GitHub-Python-Projekt korrekt von **mypy** analysiert werden kann, musst du sicherstellen, dass **mypy** deine Bibliothek findet und die Typprüfung korrekt durchführt. Hier sind die wichtigsten Schritte:

---

### **1. Stelle sicher, dass `mypy` installiert ist**
Falls `mypy` nicht installiert ist, installiere es mit:
```sh
pip install mypy
```
Oder falls du **Poetry** nutzt:
```sh
poetry add --dev mypy
```

---

### **2. Erstelle eine `mypy.ini` oder `pyproject.toml`**
Mypy benötigt eine Konfigurationsdatei, um das Projekt korrekt zu analysieren.

#### **Option 1: `mypy.ini`**
Erstelle eine Datei **`mypy.ini`** im Projekt-Root und füge Folgendes hinzu:
```ini
[mypy]
python_version = 3.11  # Setze die Python-Version deines Projekts
files = designer/ tests/  # Pfade zum Code und Tests
ignore_missing_imports = True  # Falls einige externe Imports fehlen
strict = True  # Aktiviert strenge Typprüfung
```

#### **Option 2: `pyproject.toml`**
Falls du `pyproject.toml` nutzt, kannst du die Konfiguration dort hinterlegen:
```toml
[tool.mypy]
python_version = "3.11"
files = ["designer", "tests"]
ignore_missing_imports = true
strict = true
```

---

### **3. Führe `mypy` aus**
Überprüfe dein Projekt mit:
```sh
mypy designer/ tests/
```
Falls du `make` benutzt, kannst du das in dein `Makefile` einfügen:
```make
.PHONY: mypy
mypy:  ## Run mypy type checks
	$(ENV_PREFIX)mypy designer/
```

---

### **4. In `pre-commit` Hook integrieren**
Falls du `pre-commit` benutzt, kannst du `mypy` dort einbinden:

Erstelle oder editiere `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Aktuelle Version
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
```
Danach installiere es mit:
```sh
pre-commit install
pre-commit run --all-files
```

---

### **5. In GitHub Actions (CI) einbinden**
Falls du `mypy` auch in GitHub Actions ausführen möchtest, erstelle eine Datei `.github/workflows/mypy.yml`:
```yaml
name: Mypy Type Check

on: [push, pull_request]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install mypy
          pip install -r requirements.txt
      - name: Run mypy
        run: mypy designer/
```

---

### **6. Fehler beheben**
Falls `mypy` Fehler meldet, kannst du Typannotationen ergänzen:
```python
def add(x: int, y: int) -> int:
    return x + y
```
Falls du Typen ignorieren musst:
```python
import some_library  # type: ignore
```

---

### **Fazit**
Mit diesen Schritten stellst du sicher, dass `mypy` dein GitHub-Python-Projekt analysiert, sowohl lokal als auch in **GitHub Actions** oder `pre-commit` Hooks.

🚀 **Jetzt kannst du sauberen, getypten Python-Code schreiben!**
